lookup_index = {
    "sculpture": "sculpture",
    "assemblage": "sculpture",
    "form": "sculpture",
    "texture": "sculpture",
    "carving": "sculpture",
    "piece": "sculpture",
    "work": "employment",
    "art101": "art101",
    "art 101": "art101",
    "computer programming for the arts": "art101",
    "programming for the arts": "art101",
    "intro to programming for artists": "art101",
    "art10d": "art10d",
    "art 10d": "art10d",
    "2d foundation": "art10d",
    "art10e": "art10e",
    "art 10e": "art10e",
    "3d foundation": "art10e",
    "art10f": "art10f",
    "art 10f": "art10f",
    "4d foundations": "art10f",
    "time-based art": "art10f",
    "art20h": "art20h",
    "art 20h": "art20h",
    "concepts and practice in sculpture and public art": "art20h",
    "art75": "art75",
    "art 75": "art75",
    "intro to digital video art": "art75",
    "cmpm169": "cmpm169",
    "cmpm 169": "cmpm169",
    "creative coding": "cmpm169",
    "cmpm170": "cmpm170",
    "game design studio": "cmpm170",
    "game design capstone": "cmpm170",
    "cm capstone": "cmpm170",
    "cmpm171": "cmpm170",
    "cmpm172": "cmpm170",
    "cmpm 170": "cmpm170",
    "cmpm 171": "cmpm170",
    "cmpm 172": "cmpm170",
    "cmpm179": "cmpm179",
    "cmpm 179": "cmpm179",
    "game design practicum": "cmpm179",
    "experimental gameplay": "cmpm179",
    "courses": "courses",
    "teaching": "courses",
    "instruction": "courses",
    "cst205": "cst205",
    "cst 205": "cst205",
    "multimedia programming python": "cst205",
    "cst226 ": "cst226 ",
    "cst226": "cst226 ",
    "cst 226": "cst226 ",
    "digital photography": "cst226 ",
    "cst236": "cst236",
    "cst 236": "cst236",
    "computing for digital artists": "cst236",
    "cst251": "cst251",
    "web tools": "cst251",
    "cst252": "cst252",
    "web scripting": "cst252",
    "cst351": "cst351",
    "cst 351": "cst351",
    "intro to web design": "cst351",
    "ist541": "ist541",
    "ist 541": "ist541",
    "interactive media": "ist541",
    "age": "age",
    "adrian nankivell": "age",
    "adrian": "age",
    "nankivell": "age",
    "benzy": "benzy",
    "lauren benz": "benzy",
    "lauren": "benzy",
    "brent": "brent",
    "brent townshend": "brent",
    "townshend": "brent",
    "dad": "dad",
    "ron": "dad",
    "grandpa": "grandpa",
    "grandfather": "grandpa",
    "carl": "grandpa",
    "hazel": "hazel",
    "honey": "honey",
    "grandma": "honey",
    "grandmother": "honey",
    "dorothy": "honey",
    "dot": "honey",
    "dotty": "dotty",
    "jacin": "jacin",
    "jason": "jacin",
    "jeremiah": "jeremiah",
    "jeremiah daniels": "jeremiah",
    "daniels": "jeremiah",
    "miah": "jeremiah",
    "lanier": "lanier",
    "lanier sammons": "lanier",
    "sammons": "lanier",
    "mom": "mom",
    "your mom": "mom",
    "your mother": "mom",
    "wes's mom": "mom",
    "kathryn": "mom",
    "wes's mother": "mom",
    "mama": "mom",
    "mother": "mom",
    "murray": "murray",
    "kitty": "murray",
    "step-dad": "step-dad",
    "step dad": "step-dad",
    "stepdad": "step-dad",
    "step father": "step-dad",
    "stepfather": "step-dad",
    "step-father": "step-dad",
    "dale": "step-dad",
    "wes": "wes",
    "wes modes": "wes",
    "modes": "wes",
    "rico thunder": "wes",
    "rico": "wes",
    "tico": "wes",
    "you": "wes",
    "yourself": "wes",
    "wesbot": "wes",
    "wes bot": "wes",
    "adventure club": "adventure club",
    "black rock station": "black rock station",
    "station project": "black rock station",
    "train staiton": "black rock station",
    "brc station": "black rock station",
    "brs": "black rock station",
    "co-related space": "co-related space",
    "corelated space": "co-related space",
    "costco soulmate trading outlet": "costco soulmate trading outlet",
    "costco": "costco soulmate trading outlet",
    "soulmate trading outlet": "costco soulmate trading outlet",
    "costco soulmates": "costco soulmate trading outlet",
    "camp costco": "costco soulmate trading outlet",
    "costco at burning man": "costco soulmate trading outlet",
    "shantyboat": "dotty",
    "shantyboat dotty": "dotty",
    "river boat": "dotty",
    "fomophobia": "fomophobia",
    "free skool": "free skool",
    "free skool santa cruz": "free skool",
    "free school": "free skool",
    "free school santa cruz": "free skool",
    "guerilla drive-in": "guerilla drive-in",
    "santa cruz guerilla drive-in": "guerilla drive-in",
    "gdi": "guerilla drive-in",
    "last night": "last night",
    "last night diy parade": "last night",
    "diy parade": "last night",
    "night ride": "night ride",
    "punk rafting": "punk rafting",
    "diy rafting": "punk rafting",
    "diy boating": "punk rafting",
    "punk boating": "punk rafting",
    "secret history": "secret history",
    "a secret history of american river people": "secret history",
    "river people": "secret history",
    "river project": "secret history",
    "subrosa": "subrosa",
    "subrosa community space": "subrosa",
    "subrosa anarchist space": "subrosa",
    "subrosa infoshop": "subrosa",
    "trash orchestra": "trash orchestra",
    "santa cruz trash orchestra": "trash orchestra",
    "unavoidable disaster": "unavoidable disaster",
    "books": "books",
    "novels": "books",
    "fiction": "books",
    "non-fiction": "books",
    "burning man": "burning man",
    "ttitd": "burning man",
    "dust rave": "burning man",
    "the burn": "burning man",
    "that thing in the desert": "burning man",
    "brc": "burning man",
    "black rock city": "burning man",
    "comics": "comics",
    "graphic novels": "comics",
    "illustrations": "comics",
    "sequential art": "comics",
    "family": "family",
    "relatives": "family",
    "kin": "family",
    "household": "family",
    "films": "films",
    "movies": "films",
    "cinema": "films",
    "education": "education",
    "academic background": "education",
    "school": "education",
    "employment": "employment",
    "work history": "employment",
    "projects": "projects",
    "endeavors": "projects",
    "ventures": "projects",
    "organizing": "organizing",
    "community involvement": "organizing",
    "community organizing": "organizing",
    "exhibitions": "exhibitions",
    "shows": "exhibitions",
    "presentations": "exhibitions",
    "honors": "honors",
    "awards": "honors",
    "recognitions": "honors"
}