lookup_index = {
    "benzy": "benzy",
    "lauren benz": "benzy",
    "lauren": "benzy",
    "jeremiah": "jeremiah",
    "jeremiah daniels": "jeremiah",
    "daniels": "jeremiah",
    "miah": "jeremiah",
    "age": "age",
    "adrian nankivell": "age",
    "adrian": "age",
    "nankivell": "age",
    "murray": "murray",
    "kitty": "murray",
    "hazel": "hazel",
    "brent": "brent",
    "brent townshend": "brent",
    "townshend": "brent",
    "lanier": "lanier",
    "lanier sammons": "lanier",
    "sammons": "lanier",
    "jacin": "jacin",
    "jason": "jacin",
    "subrosa": "subrosa",
    "subrosa community space": "subrosa",
    "subrosa anarchist space": "subrosa",
    "subrosa infoshop": "subrosa",
    "free skool": "free skool",
    "free skool santa cruz": "free skool",
    "free school": "free skool",
    "free school santa cruz": "free skool",
    "guerilla drive-in": "guerilla drive-in",
    "santa cruz guerilla drive-in": "guerilla drive-in",
    "trash orchestra": "trash orchestra",
    "santa cruz trash orchestra": "trash orchestra",
    "last night": "last night",
    "last night diy parade": "last night",
    "diy parade": "last night",
    "adventure club": "adventure club",
    "night ride": "night ride",
    "secret history": "secret history",
    "a secret history of american river people": "secret history",
    "river people": "secret history",
    "river project": "secret history",
    "punk rafting": "punk rafting",
    "diy rafting": "punk rafting",
    "diy boating": "punk rafting",
    "punk boating": "punk rafting",
    "co-related space": "co-related space",
    "corelated space": "co-related space",
    "fomophobia": "fomophobia",
    "black rock station": "black rock station",
    "station project": "black rock station",
    "train staiton": "black rock station",
    "brc station": "black rock station",
    "brs": "black rock station",
    "unavoidable disaster": "unavoidable disaster",
    "dotty": "honey",
    "shantyboat": "dotty",
    "shantyboat dotty": "dotty",
    "river boat": "dotty",
    "mom": "mom",
    "your mom": "mom",
    "your mother": "mom",
    "wes's mom": "mom",
    "kathryn": "mom",
    "wes's mother": "mom",
    "wes": "mom",
    "step-dad": "step-dad",
    "step dad": "step-dad",
    "stepdad": "step-dad",
    "step father": "step-dad",
    "stepfather": "step-dad",
    "step-father": "step-dad",
    "dale": "step-dad",
    "honey": "honey",
    "grandma": "honey",
    "grandmother": "honey",
    "dorothy": "honey",
    "dot": "honey",
    "dad": "dad",
    "ron": "dad",
    "cmpm179": "cmpm179",
    "cmpm 179": "cmpm179",
    "game design practicum": "cmpm179",
    "experimental gameplay": "cmpm179",
    "cmpm170-2": "cmpm170-2",
    "game design studio": "cmpm170-2",
    "game design capstone": "cmpm170-2",
    "cm capstone": "cmpm170-2",
    "cmpm170": "cmpm170-2",
    "cmpm171": "cmpm170-2",
    "cmpm172": "cmpm170-2",
    "cmpm 170": "cmpm170-2",
    "cmpm 171": "cmpm170-2",
    "cmpm 172": "cmpm170-2",
    "cmpm169": "cmpm169",
    "cmpm 169": "cmpm169",
    "creative coding": "cmpm169",
    "art10f": "art10f",
    "art 10f": "art10f",
    "4d foundations": "art10f",
    "time-based art": "art10f",
    "art101": "art101",
    "art 101": "art101",
    "computer programming for the arts": "art101",
    "programming for the arts": "art101",
    "intro to programming for artists": "art101",
    "cst351": "cst351",
    "cst 351": "cst351",
    "intro to web design": "cst351",
    "cst251": "cst251",
    "web tools": "cst251",
    "cst252": "cst252",
    "web scripting": "cst252",
    "cst236": "cst236",
    "cst 236": "cst236",
    "computing for digital artists": "cst236",
    "cst226 ": "cst226 ",
    "cst226": "cst226 ",
    "cst 226": "cst226 ",
    "digital photography": "cst226 ",
    "cst205": "cst205",
    "cst 205": "cst205",
    "multimedia programming python": "cst205",
    "ist541": "ist541",
    "ist 541": "ist541",
    "interactive media": "ist541",
    "art75": "art75",
    "art 75": "art75",
    "intro to digital video art": "art75",
    "art10d": "art10d",
    "art 10d": "art10d",
    "2d foundation": "art10d",
    "art10e": "art10e",
    "art 10e": "art10e",
    "3d foundation": "art10e",
    "art20h": "art20h",
    "art 20h": "art20h",
    "concepts and practice in sculpture and public art": "art20h"
}